### ISSUE TITLE
All source code is showing doubled lines

### ISSUE THREAD

**Issue by jsgf** [warsus/lions-#1]
I'm using Chrome 15 on Linux, and I'm seeing the same on Firefox 7.

For example:

0103: #define USIZE   16              /\* size of user block (_64) */
0103: #define USIZE   16              /_ size of user block (_64) */
0104: #define NULL    0
0104: #define NULL    0
0105: #define NODEV   (-1)
0105: #define NODEV   (-1)
0106: #define ROOTINO 1               /_ i number of all roots _/
0106: #define ROOTINO 1               /_ i number of all roots _/
0107: #define DIRSIZ  14              /_ max characters per directory _/
0107: #define DIRSIZ  14              /_ max characters per directory */

**Comment by warsus** [comment]
Oh thanks for pointing that one out, should be fixed.
